// Generate Swagger or OpenAPI document
import swaggerUI from 'swagger-ui-express'
import swaggerJsDoc from 'swagger-jsdoc'

const options = {
  swaggerDefinition: {
    info: {
      swagger: '2.0',
      title: 'API',
      version: '1.0.0',
      description: 'Autogenerated Swagger doc'
    },
    basePath: '/api/',
    securityDefinitions: {
			jwt: {
				description: 'Standard Authorization header using the Bearer scheme. Example: \"{token}\". No need to add prefix like "bearer"!',
				type: 'apiKey',
				in: 'header',
				name: 'x-auth'
			}
		}	
  },
  apis: ['./routes/*.js']
}

const specs = swaggerJsDoc(options)

export default function (app) {
  app.use('/api-docs',swaggerUI.serve, swaggerUI.setup(specs))
}